import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import game from "../helpers/game";
export default function Home() {
  const uwu = new game("justin", "notJustin");

  const players = [uwu.player1, uwu.player2];

  const [turns, setTurns] = useState("");

  console.log(uwu.isGameOver());

  function handleEndTurn() {
    players.reverse();
    console.log(players);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Flesh and Blood Tutorial</h1>
        <form
          onSubmit={(e) => {
            e.preventDefault();
          }}
        >
          <input name="name" placeholder="Player Name" />
          <button>Submit</button>
        </form>
        <button onClick={() => handleEndTurn()}>End turn</button>
      </main>
    </div>
  );
}
