import Head from "next/head";
import styles from "../styles/Home.module.css";
import game from "../helpers/game";
export default function Home() {
  const uwu = new game("justin", "notJustin");
  console.log(uwu);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Flesh and Blood Tutorial</h1>
        <form
          onSubmit={(e) => {
            e.preventDefault();
          }}
        >
          <input name="name" placeholder="Player Name" />
          <button>Submit</button>
        </form>
      </main>
    </div>
  );
}
